language: node_js

node_js:
  - '14'
  
cache: npm

services:
  - mysql

branches:
  only:
    - master

env:
  global:
    - DB_USERNAME=root
    - DB_PASSWORD=
    - DB_PORT=3306

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS test_authz_advance;'

install:
- npm i

script:
  - npm run lint
  - npm test

after_success: npm run test:coverage:coveralls
